name: MPI demo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install MPI
        run: |
          sudo apt-get update 
          sudo apt-get install -y openmpi-common openmpi-bin
      - name: Run MPI
        run: |
          mpiexec -np 4 hostname
          
